### ISSUE TITLE
OpenAPI extension 

### ISSUE THREAD

**Issue by guersam** [zio/zio-http#2572]
I'd like to add [OpenAPI extensions](https://swagger.io/docs/specification/openapi-extensions/) to endpoints, especially for [GPTs Actions](https://platform.openai.com/docs/actions/consequential-flag).

### Example

```yaml
/api/some/resource:
  get:
    operationId: blah
    x-openai-isConsequential: false
  post:
    operationId: blah2
    x-openai-isConsequential: true
```
