### ISSUE TITLE
[gen] accept OpenAPI "open" types like "any" & "anyObject"

### ISSUE THREAD

**Issue by hochgi** [zio/zio-http#3199]
defining "Any" in OpenAPI according to the docs: https://swagger.io/docs/specification/v3_0/data-models/data-types/
<img width="759" alt="Screenshot 2024-11-06 at 8 50 01" src="https://github.com/user-attachments/assets/58770dc0-8db4-4e57-acbe-3a1a53b86b9a">

These won't work in zio-http-gen.

Expectation:
```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        name:
          type: string
        anything: {}
```
should be rendered as:
```scala
case class Foo(name: String, anything: Any)
```

Also, support "free form objects:
<img width="743" alt="Screenshot 2024-11-06 at 17 33 55" src="https://github.com/user-attachments/assets/f8047c3b-fe22-4ce1-88b1-29251f5f5fad">
e.g:
```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        name:
          type: string
        anything:
          type: object
          additionalProperties: {} # or true, or nothing at all
```
should be rendered as:
```scala
case class Foo(name: String, anything: Map[String, Any])
```

Also, since `Any` is not really nice to use, and a more common use case would be to generate with Json:
```scala
case class Foo(name: String, anything: Json)
```
or:
```scala
case class Foo(name: String, anything: Json.Obj)
```
instead of `Any`/`Map[String, Any]`…

we should add an ability to configure this.
Obviously we need to provide a way to generate a zio-json compatible code,
but perhaps other Json ASTs could be supported (like circe/playjson/etc'…)?
This controls both the code, and the required imports.

default should be `Any`/`Map[String, Any]`, since it would be surprising to generate code that would fail to compile unless you add a 3rd party dependency.
